### ISSUE TITLE
mbtiles builds failing for some orthomosaics 

### ISSUE THREAD

**Issue by ethanwhite** [weecology/EvergladesTools#116]
There are a number of cases where orthomosaics are not correctly being turned into mbtiles files. The associate error is:

```
Creating mbtiles file
  0%|                                                                                                                   | 0/78505 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/bin/rio", line 8, in <module>
    sys.exit(main_group())
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/mbtiles/scripts/cli.py", line 581, in mbtiles
    process_tiles(
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/mbtiles/cf.py", line 49, in process_tiles
    init_mbtiles()
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/mbtiles/scripts/cli.py", line 478, in init_mbtiles
    cur.execute("SELECT * FROM metadata WHERE name = 'bounds';")
sqlite3.OperationalError: no such table: metadata
```

Known examples from #108 (so far):

- 6thBridge, 2021-03-11
- Joule, 2020-04-07
- Joule, 2020-03-31
- JetPortSouth, 2021-06-07
- JetPortSouth, 2021-06-20
- JetPortSouth, 2021-06-27
- StartMel, 2022-03-30

**Comment by ethanwhite** [comment]
This was an issue cause by hacking around an issue with a previous version of rio. In the previous version the output file had to exist before it could be written into. Therefore we created a blank file. Now this is no longer required and it appears that when an empty file exists rio try's to look in a metadata table that doesn't exist and errors. I'll submit a PR with a bunch of improvements to `upload_mapbox.py` that fixes this.
