### ISSUE TITLE
6thBridge_04_01_2020 erroring in predict.py

### ISSUE THREAD

**Issue by ethanwhite** [weecology/EvergladesTools#125]
Probably needs the an alpha channel removed:

```python
Traceback (most recent call last):
  File "/blue/ewhite/everglades/EvergladesTools/Zooniverse/predict.py", line 78, in <module>
    result = run(proj_tile_path=path, checkpoint_path=checkpoint_path, savedir=savedir)
  File "/blue/ewhite/everglades/EvergladesTools/Zooniverse/predict.py", line 57, in run
    boxes = model.predict_tile(raster_path=proj_tile_path, patch_overlap=0, patch_size=1500)
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/deepforest/main.py", line 342, in predict_tile
    result = predict.predict_tile(model=self.model,
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/deepforest/predict.py", line 188, in predict_tile
    boxes = predict_image(model=model, image=crop, return_plot=False, device=device)
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/deepforest/predict.py", line 39, in predict_image
    prediction = model(image)
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/torchvision/models/detection/retinanet.py", line 496, in forward
    images, targets = self.transform(images, targets)
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/torchvision/models/detection/transform.py", line 111, in forward
    image = self.normalize(image)
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/torchvision/models/detection/transform.py", line 136, in normalize
    return (image - mean[:, None, None]) / std[:, None, None]
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0
```

**Comment by ethanwhite** [comment]
See #124
