### ISSUE TITLE
Fix orthomosaic projection issues

### ISSUE THREAD

**Issue by ethanwhite** [weecology/EvergladesTools#130]
## No projections

- [x] JetportNew_03_29_2022.tif
- [x] 3BRamp080_03_09_2022.tif
- [x] Jerrod_03_03_2021.tif
- [x] CypressCity_03_11_2022.tif
- [x] Hidden_03_29_2022.tif
- [x] Hidden_03_24_2022.tif

## Has projection but throwing projection related error

* Hidden_03_22_2021.tif

```
Traceback (most recent call last):
  File "/blue/ewhite/everglades/EvergladesTools/Zooniverse/predict.py", line 78, in <module>
    result = run(proj_tile_path=path, checkpoint_path=checkpoint_path, savedir=savedir)
  File "/blue/ewhite/everglades/EvergladesTools/Zooniverse/predict.py", line 57, in run
    boxes = model.predict_tile(raster_path=proj_tile_path, patch_overlap=0, patch_size=1500)
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/deepforest/main.py", line 342, in predict_tile
    result = predict.predict_tile(model=self.model,
  File "/blue/ewhite/ethanwhite/miniconda3/envs/EvergladesTools3/lib/python3.9/site-packages/deepforest/predict.py", line 174, in predict_tile
    image = rio.open(raster_path).read()
  File "rasterio/_io.pyx", line 367, in rasterio._io.DatasetReaderBase.read
  File "rasterio/_io.pyx", line 704, in rasterio._io.DatasetReaderBase._read
rasterio.errors.RasterioIOError: Read or write failed. /blue/ewhite/everglades/projected_mosaics/2021/SmallerColonies/Hidden_03_22_2021_projected.tif, band 1: IReadBlock failed at X offset 0, Y offset 0: TIFFReadEncodedStrip() failed.
```

**Comment by ethanwhite** [comment]
This files have all currently been moved to `theirfilename.tif.bad` to pull them out of the pipeline.

**Comment by henrykironde** [comment]
@bw4sz I have removed then alpha channel, could you sync these files and let me know

**Comment by henrykironde** [comment]
Fixed
